language: rust
cache: cargo
rust:
  - 1.33.0
  - stable
  - beta
  - nightly

jobs:
  include:
    - rust: nightly
      name: "Test minimal dependency versions with Rust nightly"
      script: cargo test -Zminimal-versions --verbose --all-features
    - rust: stable
      name: "Lint with Clippy"
      install: rustup component add clippy
      script:
        - cargo clippy --verbose --all-targets --no-default-features
        - cargo clippy --verbose --all-targets --all-features

install: skip
script:
  - cargo test --verbose --all-features
  - cargo test --verbose --no-default-features
