[package]

name = "ascii"
version = "0.6.0"
authors = ["Thomas Bahn <thomas@thomas-bahn.net>",
           "Torbj√∏rn Birch Moltu <t.b.moltu@lyse.net>",
           "Simon Sapin <simon.sapin@exyr.org>"]

description = "`Ascii` type and related functionality, previously in `std::ascii`."
documentation = "https://tomprogrammer.github.io/rust-ascii/ascii/index.html"
license = "Apache-2.0 / MIT"
repository = "https://github.com/tomprogrammer/rust-ascii"

[features]
unstable = []
